### ISSUE TITLE
Análisis precargado para tener un punto de inicio en el análisis de presupuesto

### ISSUE THREAD

**Issue by tlacoyodefrijol** [acij-ar/monitor-presupuestario#23]
Cuando inicio a conocer el presupuesto, puedo observar un análisis hecho, para saber cómo se ha asignado para distintos temas

**Comment by tlacoyodefrijol** [comment]
En el recuadro de Ejemplo de análisis se coloca el código de visualización con filtros fijos (no se muestran elementos de selección)

**Comment by tlacoyodefrijol** [comment]
Este issue se cierra, se agrega #41 para guiar a usuarixs en el primer uso de la herramienta.

**Comment by iheredia** [comment]
@tlacoyodefrijol bien. Lo cierro entonces 👍
