### ISSUE TITLE
Edición de textos para FAQ

### ISSUE THREAD

**Issue by tlacoyodefrijol** [acij-ar/monitor-presupuestario#35]
Necesitamos que el equipo de ACIJ pueda editar fácilmente el texto de la sección Dudas, siguiendo la estructura del sitio.

**Comment by tlacoyodefrijol** [comment]
- Agregar tabla con preguntas y respuestas
- Mostrar una vista con la tabla que contenga la pregunta con el botón editar
- Al dar click en editar abrir un modal para editar la pregunta y guardar
- Permitir agregar o eliminar preguntas

**Comment by tlacoyodefrijol** [comment]
@iheredia este ya está, no?

**Comment by iheredia** [comment]
@tlacoyodefrijol no. De mi lado no hice nada todavia de esto. 
Puedo empezar a hacer el front para esto. @emanuelzh pudiste armar una tabla en mysql para guardar las preguntas y respuestas?

**Comment by tlacoyodefrijol** [comment]
Este se liga a #40 con base en lo que defina @emanuelzh de la BD

**Comment by emanuelzh** [comment]
El create de la tabla esta listo
